version: 2.1

orbs:
  node: cloudify/public-unittest-orb@1 #orb version

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi


executors:
  py36:
    docker:
      - image: circleci/python:3.6

commands: 
  release: 
    steps:
    - run: 
        name: Trigger Jenkins Pipeline Upload to PyPi
        command: |
           curl $JENKINS_URL \
           --user $JENKINS_USER:$JENKINS_TOKEN \
           --data BRANCH=main \
           --data GITHUB_PROJECT_URL=$GH_REPO

    - run: 
        name: Trigger Jenkins Pipeline Build NE Lint for Linux x86_64
        command: |
           curl $CFY_BUILD_LINUX_URL \
           --user $JENKINS_USER:$JENKINS_TOKEN \
           --data ARCH=x86_64
    
    - run: 
        name: Trigger Jenkins Pipeline Build NE Lint for Linux aarch64
        command: |
           curl $CFY_BUILD_LINUX_URL \
           --user $JENKINS_USER:$JENKINS_TOKEN \
           --data ARCH=aarch64

    - run:
        name: Trigger Jenkins Pipeline Build NE Lint for Macos x86_64
        command: |
           curl $CFY_BUILD_MACOS_URL \
           --user $JENKINS_USER:$JENKINS_TOKEN \
           --data ARCH=macos-x86_64
    
    - run:
        name: Trigger Jenkins Pipeline Build NE Lint for Macos aarch64
        command: |
           curl $CFY_BUILD_MACOS_URL \
           --user $JENKINS_USER:$JENKINS_TOKEN \
           --data ARCH=macos-aarch64

jobs:

  release:
    executor: py36
    steps: 
      - release

workflows:
  version: 2
  tests:
    jobs:
      - node/unittests_job
      - release: 
          context:
            - cfy-lint
          filters:
            branches:
              only: main
          requires:
          - node/unittests_job

  nightly:
    triggers:
    - schedule:
        cron: "0 1 * * 0,1,3,5"
        filters:
          branches:
            only:
              - master
    jobs:
      - node/unittests_job

