version: 2.1

job-post-steps: &job-post-steps
  post-steps:
   - slack/notify_failed

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  ne: plugins/nativeedge-plugins-orb@0.0.14
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:
  py36:
    docker:
      - image: circleci/python:3.6

commands: 
  release:
    steps:
      - run:
          name: Create Wheel
          command: pip wheel .
      - run:
          name: Create new version
          command: |
            VERSION="$(cat project/ne_lint/__version__.py | grep "=" | awk '{print $3}')"
            # CREATE THE RELEASE
            URL="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/releases"
            DATA='{"tag_name":'${VERSION}',"target_commitish":"main","name":'${VERSION}',"body":"NewRelease","draft":false,"prerelease":false,"generate_release_notes":true}'
            RESP=`curl -L -X POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${GITHUB_TOKEN}" $URL -d $DATA`
            # UPLOAD THE WHEEL
            RELEASE_ID=`echo $RESP | jq '.id'`
            URL="https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${RELEASE_ID}/assets?name=ne_lint-${VERSION}-py3-none-any.whl"
            curl -L -X POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${GITHUB_TOKEN}" $URL --data-binary "@ne_lint-${VERSION}-py3-none-any.whl"

jobs:

  release:
    executor: py36
    steps: 
      - release

workflows:
  version: 2.1
  tests:
    jobs:
      - ne/unittests_job:
          context:
            - plugins-inputs
          <<: *unittest-post-steps
      - release:
          filters:
            branches:
              only: main
          requires:
            - ne/unittests_job
