version: 2.1

job-post-steps: &job-post-steps
  post-steps:
   - slack/notify_failed

unittest-post-steps: &unittest-post-steps
  post-steps:
    - store_test_results:
        path: /home/circleci/project/nosetests.xml
    - store_artifacts:
        path: /home/circleci/project/coverage.xml
        prefix: tests
    - slack/notify_failed

orbs:
  ne: plugins/nativeedge-plugins-orb@0.0.14
  slack: cloudify/notify-slack@2

checkout:
  post:
    - >
      if [ -n "$CI_PULL_REQUEST" ]; then
        PR_ID=${CI_PULL_REQUEST##*/}
        git fetch origin +refs/pull/$PR_ID/merge:
        git checkout -qf FETCH_HEAD
      fi

executors:
  py36:
    docker:
      - image: circleci/python:3.6

commands: 
  release:
    steps:
      - run: 
          name: Trigger Jenkins Pipeline Upload to PyPi
          command: |
            curl $JENKINS_URL \
            --user $JENKINS_USER:$JENKINS_TOKEN \
            --data BRANCH=main \
            --data GITHUB_PROJECT_URL=$GH_REPO

      - run: 
          name: Trigger Jenkins Pipeline Build NE Lint for Linux x86_64
          command: |
            curl $CFY_BUILD_LINUX_URL \
            --user $JENKINS_USER:$JENKINS_TOKEN \
            --data ARCH=x86_64
      
      - run: 
          name: Trigger Jenkins Pipeline Build NE Lint for Linux aarch64
          command: |
            curl $CFY_BUILD_LINUX_URL \
            --user $JENKINS_USER:$JENKINS_TOKEN \
            --data ARCH=aarch64

      - run:
          name: Trigger Jenkins Pipeline Build NE Lint for Macos x86_64
          command: |
            curl $CFY_BUILD_MACOS_URL \
            --user $JENKINS_USER:$JENKINS_TOKEN \
            --data ARCH=macos-x86_64
      
      - run:
          name: Trigger Jenkins Pipeline Build NE Lint for Macos aarch64
          command: |
            curl $CFY_BUILD_MACOS_URL \
            --user $JENKINS_USER:$JENKINS_TOKEN \
            --data ARCH=macos-aarch64

jobs:

  release:
    executor: py36
    steps: 
      - release

workflows:
  version: 2.1
  tests:
    jobs:
      - ne/unittests_job:
          context:
            - plugins-inputs
          <<: *unittest-post-steps
      - release:
          context:
            - cfy-lint
          filters:
            branches:
              only: main
          requires:
            - ne/unittests_job
